/**
 * Location dataset types — committed snapshot schema (design §5.2).
 *
 * Source: `app/docs/design/sprint-11-seo-content-engine.md` §5.2 (TASK-303).
 * Generated by the geodata pipeline (`apps/web/scripts/geodata/`, `pnpm geo:sync`)
 * from GeoNames (CC BY 4.0) + SimpleMaps Basic (CC BY 4.0) + Wikidata (CC0).
 * Pages read the committed `locations.json` snapshot only — no runtime
 * third-party calls (deterministic builds).
 */

import type { Locale } from '@joinorigin/i18n';

export type { Locale };

/** A country entry (GeoNames `countryInfo.txt`, §5.2). */
export interface LocationCountry {
  iso2: string;
  iso3: string;
  name: string;
  asciiName: string;
  continent: string;
  capital: string;
  population: number;
  currency: string;
  languages: string[];
  tld: string;
  geonameId: number;
  /** 21-locale localized names (Wikidata → GeoNames alternates → EN). */
  names: Record<Locale, string>;
}

/** An admin-1 region entry (`admin1CodesASCII.txt`, §5.2). */
export interface LocationRegion {
  /** `${iso2}-${admin1Code}` e.g. "us-tx". */
  id: string;
  name: string;
  asciiName: string;
  countryIso2: string;
  admin1Code: string;
  geonameId: number;
  population?: number;
  names: Record<Locale, string>;
}

/** A city entry (GeoNames `cities500` + SimpleMaps overlay + Wikidata, §5.2). */
export interface LocationCity {
  /** GeoNames geonameId. */
  id: number;
  /** Wikidata QID when known (via GeoNames `wkdt` alternate names). */
  qid?: string;
  name: string;
  asciiName: string;
  lat: number;
  lng: number;
  countryIso2: string;
  regionId: string;
  population?: number;
  timezone: string;
  /** GeoNames feature code: PPLC | PPLA | PPLA2 | PPLA3 | PPLA4 | PPL | … */
  featureCode: string;
  /** SimpleMaps capital tier. */
  capital: 'primary' | 'admin' | 'minor' | '';
  /** SimpleMaps importance ranking (1–5) when the source provides it. */
  ranking?: 1 | 2 | 3 | 4 | 5;
  /** True when another city in the snapshot shares the same ascii name. */
  sameName: boolean;
  names: Record<Locale, string>;
}

/** Dataset source provenance, pinned for the snapshot. */
export interface LocationSources {
  geonames: string;
  simplemaps: string;
  wikidata: string;
}

/** Top-level committed snapshot (`locations.json`). */
export interface LocationSnapshot {
  /** Dataset version date (deterministic `lastmod` source — never `new Date()` at runtime). */
  version: string;
  sources: LocationSources;
  countries: LocationCountry[];
  regions: LocationRegion[];
  cities: LocationCity[];
}

/**
 * Required footer attribution (design §5.4 — non-negotiable licensing
 * condition for GeoNames + SimpleMaps Basic, CC BY 4.0). Location pages
 * render this string in the footer; see `NOTICE` next to the snapshot.
 */
export const LOCATION_ATTRIBUTION =
  'Location data © GeoNames contributors, CC BY 4.0; city data © SimpleMaps (worldcities basic), CC BY 4.0.';
